src/Pages/Admin/DeleteGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteGameModel : PageModel
    {
        private readonly IGameRepository _gameRepository;

        [BindProperty]
        public GameViewModel GameToDelete { get; set; } = new GameViewModel();

        public DeleteGameModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }
        

        public async Task OnGet(Guid GameId)
        {
            var Game = await _gameRepository.GetGameAsync(GameId) ?? new Game();

            GameToDelete.GameId = Game.GameId;
            GameToDelete.Team1Name = Game.Team1Name;
            GameToDelete.Team2Name = Game.Team2Name;
            GameToDelete.Team1Score = Game.Team1Score;
            GameToDelete.Team2Score = Game.Team2Score;
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Game = await _gameRepository.GetGameAsync(GameToDelete.GameId) ?? new Game();
            if(Game != new Game())
            {
                await _gameRepository.DeleteGameAsync(Game.GameId);                
            }
           
            return RedirectToPage("/Admin/Games");
        }
    }
}

src/Pages/Admin/EditGame.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class EditGameModel : PageModel
    {        
        private readonly IGameRepository _gameRepository;

        [BindProperty]
        public Game GameToEdit { get; set; } = new();

        public EditGameModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }

        public async Task OnGet(Guid GameId)
        {
            GameToEdit = await _gameRepository.GetGameAsync(GameId) ?? new Game();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            GameToEdit.Player1WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? GameToEdit.Team1Player1Id : GameToEdit.Team2Player1Id;
            GameToEdit.Player2WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? GameToEdit.Team1Player2Id : GameToEdit.Team2Player2Id;

            // The following code has been added to ensure that no winner is selected in the case of a tie
            if (GameToEdit.Team1Score == GameToEdit.Team2Score)
            {
                GameToEdit.Player1WinnerId = Guid.Empty;
                GameToEdit.Player2WinnerId = Guid.Empty;
            }

            await _gameRepository.UpdateGameAsync(GameToEdit);
            return RedirectToPage("/Admin/Games");
        }
    }
}

src/Pages/Admin/GamePlay/AddGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Versioning;
using PingPongTracker.Data;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    [Authorize(Roles = "Admin")]
    public class AddGameModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public GameViewModel GameToAdd { get; set; } = new GameViewModel();

        public SelectList TeamSelectList { get; set; } = new SelectList(new List<TeamOptionViewModel>());

        public AddGameModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            TeamSelectList = GetTeamOptions();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            TeamSelectList = GetTeamOptions();

            var Team1 = _context.Teams.Find(GameToAdd.Team1Id) ?? new Team();
            var Team2 = _context.Teams.Find(GameToAdd.Team2Id) ?? new Team();
            var CurrentSeason = _context.Seasons.Where(s => s.Active == true).FirstOrDefault() ?? new Season();

            var NewGame = new TourneyGame
            {
                Team1Name = GetTeamOptions().First(t => t.Value == GameToAdd.Team1Id.ToString()).Text,
                Team1Player1Id = Team1.Player1Id,
                Team1Player2Id = Team1.Player2Id,
                Team2Name = GetTeamOptions().First(t => t.Value == GameToAdd.Team2Id.ToString()).Text,
                Team2Player1Id = Team2.Player1Id,
                Team2Player2Id = Team2.Player2Id,
                Team1Score = GameToAdd.Team1Score,
                Team2Score = GameToAdd.Team2Score,
                Player1WinnerId = GameToAdd.Team1Score > GameToAdd.Team2Score ? Team1.Player1Id : Team2.Player1Id,
                Player2WinnerId = GameToAdd.Team1Score > GameToAdd.Team2Score ? Team1.Player2Id : Team2.Player2Id,
                MatchupDate = DateTime.Now,
                SeasonId = CurrentSeason.SeasonId
            };

            _context.TourneyGames.Add(NewGame);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/GamePlay/Tournament");
        }




        private SelectList GetTeamOptions()
        {
            List<TeamOptionViewModel> TeamOptions = new List<TeamOptionViewModel>();

            foreach (Team team in _context.Teams)
            {
                TeamOptions.Add(new TeamOptionViewModel
                {
                    Value = team.TeamID,
                    Text = GamePlayUtilities.CreateTeamName(team.Player1UserName, team.Player2UserName)
                });
            }

            return new SelectList(TeamOptions, "Value", "Text");
        }
    }
}

src/Pages/Admin/GamePlay/AddTeam.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    public class AddTeamModel : PageModel
    {
        private readonly ITeamRepository _teamRepository;
        private readonly IPlayerRepository _playerRepository;

        [BindProperty]
        public Team TeamToAdd { get; set; } = new Team();

        public SelectList ListOfPlayers { get; set; } = new SelectList(new List<SelectListItem>());

        public AddTeamModel(ITeamRepository teamRepository,IPlayerRepository playerRepository)
        {
            _teamRepository = teamRepository;
            _playerRepository = playerRepository;
        }
        
        
        public void OnGet()
        {
            ListOfPlayers = GetPlayerOptions();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ListOfPlayers = GetPlayerOptions();

            var NewTeam = new Team
            {
                Player1Id = TeamToAdd.Player1Id,
                Player1UserName = ListOfPlayers.First(p => p.Value == TeamToAdd.Player1Id.ToString()).Text,
                Player2Id = TeamToAdd.Player2Id,
                Player2UserName = ListOfPlayers.First(p => p.Value == TeamToAdd.Player2Id.ToString()).Text
            };

            await _teamRepository.AddTeamAsync(NewTeam);            

            return RedirectToPage("/Admin/GamePlay/Tournament");
        }


        private SelectList GetPlayerOptions()
        {
            var Players = _playerRepository.GetActivePlayers();
            var PlayerOptions = from player in Players
                                select new SelectListItem
                                {
                                    Value = player.PlayerId.ToString(),
                                    Text = player.UserName
                                };

            return new SelectList(PlayerOptions, "Value", "Text");
        }
    }
}

src/Pages/Admin/GamePlay/DeleteGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    [Authorize(Roles = "Admin")]
    public class DeleteGameModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public GameViewModel GameToDelete { get; set; } = new GameViewModel();

        public DeleteGameModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet(Guid GameId)
        {
            var Game = _context.TourneyGames.Find(GameId) ?? new TourneyGame();

            GameToDelete.GameId = Game.GameId;
            GameToDelete.Team1Name = Game.Team1Name;
            GameToDelete.Team2Name = Game.Team2Name;
            GameToDelete.Team1Score = Game.Team1Score;
            GameToDelete.Team2Score = Game.Team2Score;
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Game = _context.TourneyGames.Find(GameToDelete.GameId) ?? new TourneyGame();

            _context.TourneyGames.Remove(Game);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/GamePlay/Tournament");
        }
    }
}

src/Pages/Admin/GamePlay/Tournament.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Extensions;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{

    [Authorize(Roles = "Admin")]
    public class TournamentModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IGameRepository _gameRepository;
        private readonly IPlayerRepository _playerRepository;
        private IEnumerable<Player> _activePlayers;

        public record EligiblePlayers(Guid PlayerId, string UserName, bool Eligible);
        [BindProperty]
        public List<Team> CurrentTeams { get; set; } = new List<Team>();
        [BindProperty]
        public List<EligiblePlayers> EligiblePlayersList { get; set; } = new();
        [BindProperty]
        public Season? CurrentSeason { get; set; }
        [BindProperty]
        public List<GameViewModel> Games { get; set; } = new List<GameViewModel>();

        public TournamentModel(ApplicationDbContext context, IPlayerRepository playerRepository, IGameRepository gameRepository)
        {
            _context = context;
            _playerRepository = playerRepository;
            _gameRepository = gameRepository;
            _activePlayers = _playerRepository.GetActivePlayers();
        }


        public void OnGet()
        {
            // If there is no active season, show nothing            
            CurrentSeason = _context.Seasons.Where(s => s.Active).FirstOrDefault();
            if (CurrentSeason != null)
            {
                // If there are Teams defined, then we are in a season. Do not show the eligible players list.
                if (_context.Teams.Count() > 0)
                {
                    CurrentTeams = _context.Teams.ToList();

                    var tourneyGames = _context.TourneyGames.ToList();
                    foreach (var game in tourneyGames)
                    {
                        Games.Add(new GameViewModel
                        {
                            GameId = game.GameId,
                            Team1Name = game.Team1Name,
                            Team2Name = game.Team2Name,
                            Team1Score = game.Team1Score,
                            Team2Score = game.Team2Score
                        });
                    }
                }
                else
                {
                    foreach (var player in _activePlayers)
                    {
                        EligiblePlayersList.Add(new EligiblePlayers(player.PlayerId, player.UserName, player.Eligible));
                    }
                }
            }
        }

        public IActionResult OnPostMakeTeams()
        {
            // Randomly add Eligible Players teams
            var eligiblePlayers = EligiblePlayersList.Where(p => p.Eligible == true).ToList();
            var random = new Random();
            var shuffledPlayers = eligiblePlayers.OrderBy(p => random.Next()).ToList();
            var CandidateTeams = new List<Team>();

            if (shuffledPlayers.Count % 2 != 0)
            {
                for (int i = 0; i < shuffledPlayers.Count - 1; i += 2)
                {
                    CandidateTeams.Add(new Team
                    {
                        Player1Id = shuffledPlayers[i].PlayerId,
                        Player1UserName = shuffledPlayers[i].UserName,
                        Player2Id = shuffledPlayers[i + 1].PlayerId,
                        Player2UserName = shuffledPlayers[i + 1].UserName
                    });
                }
                CandidateTeams.Add(new Team
                {
                    Player1Id = Guid.Empty,
                    Player1UserName = "ODD PERSON OUT",
                    Player2Id = shuffledPlayers[shuffledPlayers.Count - 1].PlayerId,
                    Player2UserName = shuffledPlayers[shuffledPlayers.Count - 1].UserName
                });
            }
            else
            {
                for (int i = 0; i < shuffledPlayers.Count; i += 2)
                {
                    CandidateTeams.Add(new Team
                    {
                        Player1Id = shuffledPlayers[i].PlayerId,
                        Player1UserName = shuffledPlayers[i].UserName,
                        Player2Id = shuffledPlayers[i + 1].PlayerId,
                        Player2UserName = shuffledPlayers[i + 1].UserName
                    });
                }
            }

            HttpContext.Session.Set<List<Team>>("CandidateTeams", CandidateTeams);
            return RedirectToPage("/Admin/GamePlay/TourneyAccept");
        }

        public async Task<IActionResult> OnPostTourneyComplete()
        {

            foreach (var TounamentGame in _context.TourneyGames)
            {
                _context.Games.Add(new Game()
                {
                    Team1Name = TounamentGame.Team1Name,
                    Team1Player1Id = TounamentGame.Team1Player1Id,
                    Team1Player2Id = TounamentGame.Team1Player2Id,
                    Team2Name = TounamentGame.Team2Name,
                    Team2Player1Id = TounamentGame.Team2Player1Id,
                    Team2Player2Id = TounamentGame.Team2Player2Id,
                    Team1Score = TounamentGame.Team1Score,
                    Team2Score = TounamentGame.Team2Score,
                    MatchupDate = TounamentGame.MatchupDate,
                    Player1WinnerId = TounamentGame.Player1WinnerId,
                    Player2WinnerId = TounamentGame.Player2WinnerId,
                    SeasonId = TounamentGame.SeasonId
                });
                _context.TourneyGames.Remove(TounamentGame);
            }
            

            _context.Teams.RemoveRange(_context.Teams);

            await _context.SaveChangesAsync();

            foreach (var player in _activePlayers)
            {
                EligiblePlayersList.Add(new EligiblePlayers(player.PlayerId, player.UserName, player.Eligible));
            }

            return RedirectToPage("/Index");
        }
    }
}

src/Pages/Admin/GamePlay/TourneyAccept.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Extensions;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    public class TourneyAcceptModel : PageModel
    {
        private readonly ITeamRepository _teamRepository;

        [BindProperty]
        public List<Team> ProposedTeams { get; set; } = new List<Team>();        
        
        public TourneyAcceptModel(ITeamRepository teamRepository)
        {
            _teamRepository = teamRepository;
        }        
        
        public void OnGet(Guid id)
        {
            ProposedTeams = HttpContext.Session.Get<List<Team>>("CandidateTeams");
        } 

        public async Task<IActionResult> OnPostAcceptTeams()
        {
            ProposedTeams = HttpContext.Session.Get<List<Team>>("CandidateTeams");
            await _teamRepository.AddRangeAsync(ProposedTeams);            

            return RedirectToPage("Tournament");
        }    

        public IActionResult OnPostNewTeams()
        {
            // Delete the teams
            HttpContext.Session.Set<List<Team>>("CandidateTeams", new List<Team>());
            
            return RedirectToPage("Tournament");
        }   
    }
}

src/Pages/Admin/GamePlay/AddGame.cshtml
@page
@model PingPongTracker.Pages.Admin.GamePlay.AddGameModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Add a Game";
}

<div class="text-center">
    <h3 class="display-4">Add Game</h3>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="GameToAdd.GameId" />
            </div>
            <div class="row">
                <div class="col-md-9 col-9">
                    <label for="Team1Id" class="form-label col-form-label-sm">Visitors</label>
                    <select class="form-control form-control-sm" asp-for="GameToAdd.Team1Id"
                        asp-items="Model.TeamSelectList"></select>
                </div>
                <div class="col-md-3 col-3">
                    <label for="Team1Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToAdd.Team1Score" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-9 col-9">
                    <label for="Team2Id" class="form-label col-form-label-sm">Home</label>
                    <select class="form-control form-control-sm" asp-for="GameToAdd.Team2Id"
                        asp-items="Model.TeamSelectList"></select>
                </div>
                <div class="col-md-3 col-3">
                    <label for="Team2Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToAdd.Team2Score" />
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-lg btn-primary">Add Game</button>
        </form>
    </div>
</div>

<br />
<p>
<h5><a asp-page="/Admin/GamePlay/Tournament">Cancel - Return to Tournament</a></h5>
</p>

src/Pages/Admin/GamePlay/AddTeam.cshtml
@page
@model PingPongTracker.Pages.Admin.GamePlay.AddTeamModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Add a Team";
}

<div class="text-center">
    <h3 class="display-4">Add Team</h3>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="TeamToAdd.TeamID" />
            </div>
            <div class="row">
                <div class="col-md-9 col-9">
                    <label for="Player1Id" class="form-label col-form-label-sm">Player 1</label>
                    <select class="form-control form-control-sm" asp-for="TeamToAdd.Player1Id"
                        asp-items="Model.ListOfPlayers"></select>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-9 col-9">
                    <label for="Player2Id" class="form-label col-form-label-sm">Player 2</label>
                    <select class="form-control form-control-sm" asp-for="TeamToAdd.Player2Id"
                        asp-items="Model.ListOfPlayers"></select>
                </div>                    
            </div>
            <br />
            <button type="submit" class="btn btn-lg btn-primary">Add Team</button>
        </form>
    </div>
</div>

<br />
<p>
<h5><a asp-page="/Admin/GamePlay/Tournament">Cancel - Return to Tournament</a></h5>
</p>

src/Pages/Admin/GamePlay/DeleteGame.cshtml
@page
@model PingPongTracker.Pages.Admin.GamePlay.DeleteGameModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Delete a Game";
}

<div class="text-center">
    <h3 class="display-4">Delete Game</h3>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="GameToDelete.GameId" />
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team1Name" class="form-label col-form-label-sm">Team 1</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToDelete.Team1Name" readonly/>
                </div>
                <div class="col-md-3">
                    <label for="Team1Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToDelete.Team1Score" readonly/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team2Name" class="form-label col-form-label-sm">Team 2</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToDelete.Team2Name" readonly/>
                </div>
                <div class="col-md-3">
                    <label for="Team2Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToDelete.Team2Score" readonly/>
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-lg btn-danger">Delete Game</button>
        </form>
    </div>
</div>

<br />
<p>
<h5><a asp-page="/Admin/GamePlay/Tournament">Cancel - Return to Tournament</a></h5>
</p>

src/Pages/Admin/GamePlay/Tournament.cshtml
@page
@model PingPongTracker.Pages.Admin.GamePlay.TournamentModel
@{
    ViewData["Title"] = "Prepare a Tournament";
}

<div class="text-center">
    <h3 class="display-4">Tournament</h3>
</div>

<br />
<br />

@if (@Model.CurrentSeason == null)
{
    <div class="text-center">
    <h3 class="display-4">No Season</h3>
    <p>There is no current season. Please create a season first.</p>
    <a class="btn btn-primary" asp-page="/Admin/Seasons">Go To Seasons Page</a>
</div>
}

@if (@Model.CurrentSeason is not null && @Model.CurrentTeams.Count() == 0)
{
    <div class="text-center">
    <h4 class="display-6">No Active Tournament or Teams</h4>
    <h4>Please select players to create a new tournament</h4>
    <br />
    <br />
    <form class="p-2" method="post">
        @for (int i = 0; i < @Model.EligiblePlayersList.Count(); i++)
            {
                <div>
                    <input type="hidden" asp-for="@Model.EligiblePlayersList[i].PlayerId" />
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-10 col-md-6">
                        <h4><input type="text" class="form-control form-control-sm"
                                asp-for="@Model.EligiblePlayersList[i].UserName" readonly></h4>
                    </div>
                    <div class="col-2 col-md-1">
                        <input type="checkbox" class="form-control form-control-sm form-check-input"
                            asp-for="@Model.EligiblePlayersList[i].Eligible">
                    </div>
                </div>
            }
            <div class="fillerspace"></div>
            <button type="submit" class="btn btn-lg btn-success" asp-page-handler="MakeTeams">Randomize and Create
                Teams</button>
        </form>
    </div>
}


@if (@Model.CurrentSeason is not null && @Model.CurrentTeams.Count() != 0)
{
    <div class="text-center">
    <h4 class="display-7">Tournament Teams</h4>
    <br />
    <div class="row justify-content-md-center row-cols-md-4 row-cols-xs-1 g-4">
        @for (int i = 0; i < @Model.CurrentTeams.Count(); i++)
            {
                <div class="col" align="center">
                    <div class="card" style="width: 18rem;">
                        <div class="card-header">
                            <a asp-page="EditTeam" asp-route-TeamID="@Model.CurrentTeams[i].TeamID">Team @(i + 1)</a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">@Model.CurrentTeams[i].Player1UserName</li>
                            <li class="list-group-item">@Model.CurrentTeams[i].Player2UserName</li>
                        </ul>
                    </div>
                </div>
            }
        </div>
        <br />
        <br />
    </div>
    <div class="text-center">   
        <h5><a asp-page="/Admin/GamePlay/AddTeam">Add Team</a></h5>
    </div>
    <hr />
    <br />
    <br />
    <div class="text-center">
    <h3 class="display-4">Games</h3>
</div>

    <p>
<h4><a asp-page="/Admin/GamePlay/AddTourneyGame">Add Game</a></h4>
</p>

    <br />
    <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Game #</th>
            <th scope="col">Visitors</th>
            <th scope="col">Score</th>
            <th scope="col">Home</th>
            <th scope="col">Score</th>
            <th scope="col">DELETE</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < @Model.Games.Count(); i++)
            {
                <tr>
                    <td><a asp-page="EditTourneyGame" asp-route-GameId=@Model.Games[i].GameId>@(i + 1)</a></td>
                    <td>@Model.Games[i].Team1Name</td>
                    <td>@Model.Games[i].Team1Score</td>
                    <td>@Model.Games[i].Team2Name</td>
                    <td>@Model.Games[i].Team2Score</td>
                    <td><a asp-page="DeleteTourneyGame" asp-route-GameId=@Model.Games[i].GameId><strong>X</strong></a></td>
                </tr>
            }
        </tbody>
    </table>

    <div class="fillerspace"></div>
    <hr />
    <div class="text-xs-center">
    <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Tournament Complete
    </button>
</div>


    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Completing The Tournament</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                This will complete the tournament, update the season standings,
                and erase the current teams. Are you sure you want to do this?
            </div>
            <div class="modal-footer">
                <form class="p-2" method="post">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Never Mind</button>
                    <button type="submit" class="btn btn-danger" asp-page-handler="TourneyComplete">Complete</button>
                </form>
            </div>
        </div>
    </div>
</div>
}

src/Pages/Admin/GamePlay/TourneyAccept.cshtml
@page
@model PingPongTracker.Pages.Admin.GamePlay.TourneyAcceptModel
@{
    ViewData["Title"] = "Prepare a Tournament";
}

<div class="text-center">
    <h3 class="display-4">Proposed Teams for Tournament</h3>    
</div>

<br />
<br />

<div class="text-center">        
    <h4 class="display-7">Here They Are!</h4>  
    <br />   
    <div class="row justify-content-md-center row-cols-md-4 g-4"> 
        @for(int i = 0; i < @Model.ProposedTeams.Count(); i++)
        {
            <div class="col">                
                <p><strong>Team @(i+1)</strong></p>                
                <p>@Model.ProposedTeams[i].Player1UserName & @Model.ProposedTeams[i].Player2UserName</p>
            </div>
        }
    </div>
    <br />  
    <br />
    <form class="p-2" method="post" >
        <button type="submit" class="btn btn-lg btn-success" asp-page-handler="AcceptTeams">Accept Teams</button>
        <button type="submit" class="btn btn-lg btn-warning" asp-page-handler="NewTeams">Do Over</button>
    </form>  
</div>