src/Models/Game.cs
using System.ComponentModel.DataAnnotations;

namespace PingPongTracker.Models;

public class Game
{
    [Key]
    public Guid GameId { get; set; }
    [Required]
    public string Team1Name { get; set; } = "";
    [Required]
    public Guid Team1Player1Id { get; set; }
    [Required]
    public Guid Team1Player2Id { get; set; }
    [Required]
    public string Team2Name { get; set; } = "";
    [Required]
    public Guid Team2Player1Id { get; set; }
    [Required]
    public Guid Team2Player2Id { get; set; }
    [Required]
    public int Team1Score { get; set; }
    [Required]
    public int Team2Score { get; set; }
    [Required]
    public DateTime MatchupDate { get; set; } = DateTime.Now;
    [Required]
    public Guid Player1WinnerId { get; set; }
    [Required]
    public Guid Player2WinnerId { get; set; }    
    public Guid SeasonId { get; set; }
}

src/Pages/Admin/ActiveSeasonVerify.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class ActiveSeasonVerifyModel : PageModel
    {        
        private readonly ISeasonRepository _seasonRepository;
        private readonly ITeamRepository _teamRepository;
        private readonly ITourneyGameRepository _tgRepository;

        [BindProperty]
        public Season SeasonToUpdate { get; set; } = new();

        public ActiveSeasonVerifyModel(ISeasonRepository seasonRepository, ITeamRepository teamRepository, ITourneyGameRepository TGRepo)
        {            
            _seasonRepository = seasonRepository;
            _teamRepository = teamRepository;
            _tgRepository = TGRepo;
        }


        public async Task OnGet(Guid SeasonId)
        {
            SeasonToUpdate = await _seasonRepository.GetSeasonById(SeasonId);
        }

        public IActionResult OnPostNewSeasonInactive()
        {
            return RedirectToPage("Seasons");
        }

        public async Task<IActionResult> OnPostActivateNewSeason()
        {
            await _tgRepository.RemoveRange(_tgRepository.GetTourneyGames().ToList());
            _teamRepository.RemoveRange(_teamRepository.GetTeams().ToList());            

            SeasonToUpdate.Active = true;
            await _seasonRepository.UpdateSeason(SeasonToUpdate);

            return RedirectToPage("Seasons");
        }
    }
}

src/Pages/Admin/AddPlayer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class AddPlayerModel : PageModel
    {        
        private readonly IPlayerRepository _playerRepository;
        
        [BindProperty]
        public Player NewPlayer { get; set; } = new();
        
        public AddPlayerModel(IPlayerRepository playerRepository)
        {
            _playerRepository = playerRepository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }                 
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }            
            await _playerRepository.AddPlayer(NewPlayer);                        
            return RedirectToPage("Players");
        }
    }
}

src/Pages/Admin/AddSeason.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class AddSeasonModel : PageModel
    {        
        private readonly ISeasonRepository _seasonRepository;
        private readonly ITeamRepository _teamRepository;

        [BindProperty]
        public Season SeasonToAdd { get; set; } = new();

        public AddSeasonModel(ISeasonRepository Repo, ITeamRepository teamRepository)
        {            
            _seasonRepository = Repo;
            _teamRepository = teamRepository;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Are there any Teams? If there are, this indicates that a Season has already been created and that there is
            // an active torunament. Check if the SeasonToAdd is set to Active.
            if (SeasonToAdd.Active && _teamRepository.GetTeams().Any())
            {
                SeasonToAdd.Active = false;
                await _seasonRepository.AddSeason(SeasonToAdd);

                return RedirectToPage("ActiveSeasonVerify", new { SeasonId = SeasonToAdd.SeasonId });
            }

            await _seasonRepository.AddSeason(SeasonToAdd);
            return RedirectToPage("Seasons");
        }
    }
}

src/Pages/Admin/DeleteGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class DeleteGameModel : PageModel
    {
        private readonly IGameRepository _gameRepository;

        [BindProperty]
        public GameViewModel GameToDelete { get; set; } = new GameViewModel();

        public DeleteGameModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }
        

        public async Task OnGet(Guid GameId)
        {
            var Game = await _gameRepository.GetGameAsync(GameId) ?? new Game();

            GameToDelete.GameId = Game.GameId;
            GameToDelete.Team1Name = Game.Team1Name;
            GameToDelete.Team2Name = Game.Team2Name;
            GameToDelete.Team1Score = Game.Team1Score;
            GameToDelete.Team2Score = Game.Team2Score;
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Game = await _gameRepository.GetGameAsync(GameToDelete.GameId) ?? new Game();
            if(Game != new Game())
            {
                await _gameRepository.DeleteGameAsync(Game.GameId);                
            }
           
            return RedirectToPage("/Admin/Games");
        }
    }
}

src/Pages/Admin/EditGame.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class EditGameModel : PageModel
    {        
        private readonly IGameRepository _gameRepository;

        [BindProperty]
        public Game GameToEdit { get; set; } = new();

        public EditGameModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }

        public async Task OnGet(Guid GameId)
        {
            GameToEdit = await _gameRepository.GetGameAsync(GameId) ?? new Game();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            GameToEdit.Player1WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? GameToEdit.Team1Player1Id : GameToEdit.Team2Player1Id;
            GameToEdit.Player2WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? GameToEdit.Team1Player2Id : GameToEdit.Team2Player2Id;

            // The following code has been added to ensure that no winner is selected in the case of a tie
            if (GameToEdit.Team1Score == GameToEdit.Team2Score)
            {
                GameToEdit.Player1WinnerId = Guid.Empty;
                GameToEdit.Player2WinnerId = Guid.Empty;
            }

            await _gameRepository.UpdateGameAsync(GameToEdit);
            return RedirectToPage("/Admin/Games");
        }
    }
}

src/Pages/Admin/EditPlayer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.Differencing;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class EditPlayerModel : PageModel
    {
        private readonly IPlayerRepository _playerRepository;
        
        [BindProperty]
        public Player PlayerToEdit { get; set; } = new();
        
        public EditPlayerModel(IPlayerRepository repo)
        {
            _playerRepository = repo;            
        }
        
        public async Task OnGet(Guid PlayerID)
        {
            PlayerToEdit = await _playerRepository.GetPlayerById(PlayerID);
        }  

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!_playerRepository.GoodUserNameChange(PlayerToEdit))
            {
                ModelState.AddModelError(string.Empty, "Username already exists");
                return Page();
            }                                    
                                    
            await _playerRepository.UpdatePlayer(PlayerToEdit);                        
            return RedirectToPage("Players");
        }              
    }
}

src/Pages/Admin/EditSeason.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class EditSeasonModel : PageModel
    {
        private readonly ITeamRepository _teamRepository;
        private readonly ISeasonRepository _seasonRepository;

        [BindProperty]
        public Season SeasonToEdit { get; set; } = new();

        public EditSeasonModel(ISeasonRepository repo, ITeamRepository teamRepository)
        {            
            _seasonRepository = repo;
            _teamRepository = teamRepository;
        }

        public async Task OnGet(Guid SeasonID)
        {
            SeasonToEdit = await _seasonRepository.GetSeasonById(SeasonID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Are there any Teams? If there are, this indicates that a Season has already been created and that there is
            // an active torunament. Check if the SeasonToAdd is set to Active.
            if (SeasonToEdit.Active && _teamRepository.GetTeams().Any())
            {
                SeasonToEdit.Active = false;
                await _seasonRepository.UpdateSeason(SeasonToEdit);

                return RedirectToPage("ActiveSeasonVerify", new { SeasonId = SeasonToEdit.SeasonId });
            }

            await _seasonRepository.UpdateSeason(SeasonToEdit);
            return RedirectToPage("Seasons");
        }
    }
}

src/Pages/Admin/GamePlay/DeleteGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    [Authorize(Roles = "Admin")]
    public class DeleteGameModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public GameViewModel GameToDelete { get; set; } = new GameViewModel();

        public DeleteGameModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet(Guid GameId)
        {
            var Game = _context.TourneyGames.Find(GameId) ?? new TourneyGame();

            GameToDelete.GameId = Game.GameId;
            GameToDelete.Team1Name = Game.Team1Name;
            GameToDelete.Team2Name = Game.Team2Name;
            GameToDelete.Team1Score = Game.Team1Score;
            GameToDelete.Team2Score = Game.Team2Score;
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Game = _context.TourneyGames.Find(GameToDelete.GameId) ?? new TourneyGame();

            _context.TourneyGames.Remove(Game);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/GamePlay/Tournament");
        }
    }
}

src/Pages/Admin/GamePlay/EditGame.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PingPongTracker.Data;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin.GamePlay
{
    [Authorize(Roles = "Admin")]
    public class EditGameModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public GameViewModel GameToEdit { get; set; } = new GameViewModel();

        public EditGameModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public void OnGet(Guid GameId)
        {
            var Game = _context.TourneyGames.Find(GameId) ?? new TourneyGame();

            GameToEdit.GameId = Game.GameId;
            GameToEdit.Team1Name = Game.Team1Name;
            GameToEdit.Team2Name = Game.Team2Name;
            GameToEdit.Team1Score = Game.Team1Score;
            GameToEdit.Team2Score = Game.Team2Score;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var Game = _context.TourneyGames.Find(GameToEdit.GameId) ?? new TourneyGame();

            Game.Team1Score = GameToEdit.Team1Score;
            Game.Team2Score = GameToEdit.Team2Score;
            Game.Player1WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? Game.Team1Player1Id : Game.Team2Player1Id;
            Game.Player2WinnerId = GameToEdit.Team1Score > GameToEdit.Team2Score ? Game.Team1Player2Id : Game.Team2Player2Id;

            // The following code has been added to ensure that no winner is selected in the case of a tie
            if (GameToEdit.Team1Score == GameToEdit.Team2Score)
            {
                Game.Player1WinnerId = Guid.Empty;
                Game.Player2WinnerId = Guid.Empty;
            }

            _context.TourneyGames.Update(Game);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Admin/GamePlay/Tournament");
        }

    }
}

src/Pages/Admin/Games.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class GamesModel : PageModel
    {
        private readonly IGameRepository _gameRepository;

        [BindProperty]
        public List<Game> Games { get; set; } = new();

        public GamesModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }

        public void OnGet()
        {
            Games = _gameRepository.GetGames().ToList();
        }
    }
}

src/Pages/Admin/Maintenance.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static PingPongTracker.Data.MaintenanceOptions;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class MaintenanceModel : PageModel
    {
        public List<MaintenanceOption> Options { get; set; } = GetMaintenanceOptions().ToList();

        public void OnGet()
        {
        }
    }
}

src/Pages/Admin/Players.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class PlayersModel : PageModel
    {
        private readonly IPlayerRepository _playerRepository;
        
        public IEnumerable<Player> Players { get; set; } = new List<Player>();

        // constructor
        public PlayersModel(IPlayerRepository playerRepository)
        {
            _playerRepository = playerRepository;            
        }        
        
        public async Task OnGet()
        {
            Players = await _playerRepository.GetPlayers();
        }
    }
}

src/Pages/Admin/Seasons.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PingPongTracker.Data;
using PingPongTracker.Data.Interfaces;
using PingPongTracker.Models;

namespace PingPongTracker.Pages.Admin
{
    public class SeasonModel : PageModel
    {
        private readonly ISeasonRepository _seasonRepository;

        public List<Season> Seasons { get; set; } = new();
        
        public SeasonModel(ISeasonRepository seasonRepository)
        {
            _seasonRepository = seasonRepository;
        }

        public void OnGet()
        {
            Seasons = _seasonRepository.GetSeasons().OrderBy(s => s.SeasonStart).ToList();
        }
    }
}

src/Pages/Admin/ActiveSeasonVerify.cshtml
@page
@model PingPongTracker.Pages.Admin.ActiveSeasonVerifyModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Verify Activating a New Season";
}

<div class="text-center">
    <h4 class="display-5">Verify Activating a New Season</h4>
</div>

<div class="fillerspace"></div>

<div class="text-center">
    <p>There is a season currently active with a Torunament in play.</p>
    <p>Setting a new season to "Active" will <strong>remove any games and teams</strong> in the tournament and
        and close the currently active season.
    </p>
    <br />
    <br />
    <p>Would you rather make this new season "Inactive"?</p>
</div>

<div class="text-center">
    <form class="p-2" method="post">
        <div>
            <input type="hidden" asp-for="@Model.SeasonToUpdate.SeasonId" />
            <input type="hidden" asp-for="@Model.SeasonToUpdate.SeasonName" />
            <input type="hidden" asp-for="@Model.SeasonToUpdate.SeasonStart" />
            <input type="hidden" asp-for="@Model.SeasonToUpdate.Active" />
        </div>
        <button type="submit" class="btn btn-success" asp-page-handler="NewSeasonInactive">Make the New Season
            Inactve</button>
        <button type="submit" class="btn btn-danger" asp-page-handler="ActivateNewSeason">Destroy the Torunament -
            Activate this season!</button>
    </form>
</div>

src/Pages/Admin/AddPlayer.cshtml
@page
@model PingPongTracker.Pages.Admin.AddPlayerModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Add a Player";
}

<div class="text-center">
    <h3 class="display-4">Add New Player</h3>    
</div>

<div class="row">
	<div class="col-md-6">
		<form class="p-2" method="post">
			@Html.AntiForgeryToken()				
				<div class="mb-3">
					<label for="username" class="form-label col-form-label-sm">User Name</label>
					<input type="text" class="form-control form-control-sm" asp-for="NewPlayer.UserName" >
				</div>
				<div class="mb-3">
					<label for="firstname" class="form-label col-form-label-sm">First Name</label>
					<input type="text" class="form-control form-control-sm" asp-for="NewPlayer.FirstName" >
				</div>
				<div class="mb-3">
					<label for="lastname" class="form-label col-form-label-sm">Last Name</label>
					<input type="text" class="form-control form-control-sm" asp-for="NewPlayer.LastName" >						
				</div>				
				<div class="mb-1">
					<label for="eligible" class="form-label col-form-label-sm">Eligible</label>
					<input type="checkbox" class="form-control form-control-sm form-check-input"  asp-for="NewPlayer.Eligible" >						
				</div>
				<div class="mb-1">
					<label for="active" class="form-label col-form-label-sm">Active</label>
					<input type="checkbox" class="form-control form-control-sm form-check-input" asp-for="NewPlayer.Active" >						
				</div>
				<br />
				<button type="submit" class="btn btn-lg btn-primary">Submit</button>
		</form>
	</div>
</div>
<br />
<p>
    <h5><a asp-page="Players" >Cancel - Return to Players</a></h5>
</p>

src/Pages/Admin/AddSeason.cshtml
@page
@model PingPongTracker.Pages.Admin.AddSeasonModel
@{
    ViewData["Title"] = "Add Season";
}

<div class"text-center">
    <h1 class="display-4">Add Season</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label for="SeasonToAdd.SeasonName" class="form-label col-form-label-sm">Season Name</label>
                <input type="text" class="form-control form-control-sm" asp-for="SeasonToAdd.SeasonName" />
                <span asp-validation-for="SeasonToAdd.SeasonName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="SeasonToAdd.SeasonStart" class="form-label col-form-label-sm">Start Date</label>
                <input type="date" class="form-control form-control-sm" asp-for="SeasonToAdd.SeasonStart" value=@DateTime.Today.ToString("YYYY-MM-DD") />
                <span asp-validation-for="SeasonToAdd.SeasonStart" class="text-danger"></span>
            </div>
            <div class="mb-1">
                    <label for="active" class="form-label col-form-label-sm">Active</label>
                    <input type="checkbox" class="form-control form-control-sm form-check-input" asp-for="SeasonToAdd.Active" >						
				</div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<p>
    <h5><a asp-page="Seasons" >Cancel - Return to Seasons</a></h5>
</p>

src/Pages/Admin/DeleteGame.cshtml
@page
@model PingPongTracker.Pages.Admin.DeleteGameModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Delete a Game";
}

<div class="text-center">
    <h3 class="display-4">Delete Game</h3>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="GameToDelete.GameId" />
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team1Name" class="form-label col-form-label-sm">Team 1</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToDelete.Team1Name" readonly />
                </div>
                <div class="col-md-3">
                    <label for="Team1Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToDelete.Team1Score"
                        readonly />
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team2Name" class="form-label col-form-label-sm">Team 2</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToDelete.Team2Name" readonly />
                </div>
                <div class="col-md-3">
                    <label for="Team2Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToDelete.Team2Score"
                        readonly />
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-lg btn-danger">Delete Game</button>
        </form>
    </div>
</div>

<br />
<p>
<h5><a asp-page="/Admin/Games">Cancel - Return to Games</a></h5>
</p>

src/Pages/Admin/EditGame.cshtml
@page
@model PingPongTracker.Pages.Admin.EditGameModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Games";
}

<div class="text-center">
    <h1 class="display-4">Games</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <form class="p-2" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="GameToEdit.GameId" />
                <input type="hidden" asp-for="GameToEdit.MatchupDate" />
                <input type="hidden" asp-for="GameToEdit.SeasonId" />
                <input type="hidden" asp-for="GameToEdit.Team1Player1Id" />
                <input type="hidden" asp-for="GameToEdit.Team1Player2Id" />
                <input type="hidden" asp-for="GameToEdit.Team2Player1Id" />
                <input type="hidden" asp-for="GameToEdit.Team2Player2Id" />
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team1Name" class="form-label col-form-label-sm">Team 1</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToEdit.Team1Name" readonly />
                </div>
                <div class="col-md-3">
                    <label for="Team1Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToEdit.Team1Score" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <label for="Team2Name" class="form-label col-form-label-sm">Team 2</label>
                    <input type="text" class="form-control form-control-sm" asp-for="GameToEdit.Team2Name" readonly />
                </div>
                <div class="col-md-3">
                    <label for="Team2Score" class="form-label col-form-label-sm">Score</label>
                    <input type="number" class="form-control form-control-sm" asp-for="GameToEdit.Team2Score" />
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-lg btn-primary">Edit Game</button>
        </form>
    </div>
</div>

<br />
<p>
<h5><a asp-page="/Admin/Games">Cancel - Return to Games</a></h5>
</p>

src/Pages/Admin/Games.cshtml
@page
@model PingPongTracker.Pages.Admin.GamesModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Games";
}

<div class="text-center">
    <h1 class="display-4">Games</h1>
</div>

<br />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Game Id</th>
            <th scope="col">Date</th>
            <th scope="col">Visitig Team</th>
            <th scope="col">Score</th>
            <th scope="col">Home Team</th>
            <th scope="col">Score</th>
            <th scope="col">DELETE</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < @Model.Games.Count(); i++)
        {
            <tr>
                <td><a asp-page="EditGame" asp-route-GameId=@Model.Games[i].GameId>@Model.Games[i].GameId</a></td>
                <td>@Model.Games[i].MatchupDate</td>
                <td>@Model.Games[i].Team1Name</td>
                <td>@Model.Games[i].Team1Score</td>
                <td>@Model.Games[i].Team2Name</td>
                <td>@Model.Games[i].Team2Score</td>
                <td><a asp-page="DeleteGame" asp-route-GameId=@Model.Games[i].GameId><strong>X</strong></a></td>
            </tr>
        }
    </tbody>
</table>
<br />
<p>
    There are @Model.Games.Count games.
</p>